currentversion = "0.1.2"

[[place]]
file = "cookiecutter.json"
line-regex = '"version"'

[[place]]
file = "setup.cfg"
line-regex = 'current_version'

[[place]]
file = "setup.py"
line-regex = 'version'
